import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>madhouse</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <Example />
      </main>
    </>
  );
}

const posts: Post[] = [
  {
    id: 1,
    title: "Basic Tee 8-Pack",
    url: "test-example.com",
    description:
      "Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.",
    file: "/image-1.png",
    isVideo: false,
  },
  {
    id: 2,
    title: "Basic Tee",
    url: "test-example.com",
    description:
      "Look like a visionary CEO and wear the same black t-shirt every day.",
    file: "/image-2.jpg",
    isVideo: false,
  },
  {
    id: 3,
    title: "Basic Tee 8-Pack",
    url: "test-example.com",
    description:
      "Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.",
    file: "/image-3.png",
    isVideo: false,
  },
  {
    id: 4,
    title: "This form desn't work when I tab out and tab back in",
    url: "test-example.com",
    description:
      "Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.",
    file: "/image-4.png",
    isVideo: false,
  },
  {
    id: 5,
    title: "Basic Tee 8-Pack",
    url: "test-example.com",
    description:
      "make up to $3200 a month by working from your office! https://scam.me/8sd76f",
    file: "/image-5.png",
    isVideo: false,
  },
  {
    id: 6,
    title: "Website loads super slow on firefox, as per",
    url: "test-example.com",
    description:
      "Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.",
    file: "/image-6.mov",
    isVideo: true,
  },
];

interface Post {
  id: number;
  title: string;
  description: string;
  url: string;
  file?: string;
  isVideo: boolean;
  createdAt?: number;
  updatedAt?: number;
}

export function Example() {
  return (
    <div className="bg-white">
      <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
        <h2 className="sr-only">posts</h2>

        <div className=" columns-1 md:columns-2 lg:columns-3">
          {posts.map((post) => (
            <a href={`/p/${post.id}`} key={post.id}>
              <div className="relative my-4 flex flex-col gap-4 overflow-hidden rounded-lg border-4 border-gray-200 bg-white p-4">
                <div className="flex flex-row items-start justify-start">
                  <span className="mr-2 rounded-full bg-theme bg-opacity-50 px-3 py-1 font-mono text-base font-bold text-theme-dark">
                    {post.id}
                  </span>
                  <p className="flex-grow text-base font-medium text-gray-900">
                    {post.title}
                  </p>
                </div>
                <div className="max-w-full bg-gray-200 group-hover:opacity-75 ">
                  {post.isVideo ? (
                    <video
                      src={post.file}
                      className="w-full sm:w-full"
                      muted
                      controls
                    />
                  ) : (
                    <img
                      src={post.file}
                      className="w-full sm:w-full"
                      alt={post.title}
                    />
                  )}
                </div>
                <div className="flex flex-1 flex-col space-y-2">
                  <h3>
                    <span className="rounded-full bg-sky-200 px-3 py-1 text-sm font-medium text-sky-700">
                      {post.url}
                    </span>
                  </h3>
                  <p className="text-sm text-gray-500">{post.description}</p>
                </div>
              </div>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
